### ISSUE TITLE
Add Evolution-DecSync plugin

### ISSUE THREAD

**Issue by jonathanfaust** [flathub/org.gnome.Evolution#81]
The plugin can be found [here](https://github.com/39aldo39/Evolution-DecSync). I'm interested in either getting the plugin added on Flathub or getting help building a local version with the plugin.

**Comment by jonathanfaust** [comment]
I'm seeing if I can figure this out myself until someone has suggestions. I have limited experience building flatpaks. Here's where I'm stuck.

I added `org.freedesktop.Sdk.Extension.openjdk8` to `sdk-extensions` as required by `libdecsync`.

I added the following modules after `evolution-etesync`:

```
{
            "name": "libdecsync",
            "buildsystem": "simple",
            "build-commands": [
                "source /usr/lib/sdk/openjdk8/enable.sh && make",
                "source /usr/lib/sdk/openjdk8/enable.sh && sudo make install"
            ],
            "sources": [
                {
                    "type": "git",
                    "url": "https://github.com/39aldo39/libdecsync",
                    "branch": "master"
                }
            ]
        },
        {
            "name": "json-c",
            "buildsystem": "cmake",
            "sources": [
                {
                    "type": "git",
                    "url": "https://github.com/json-c/json-c.git",
                    "branch": "master"
                }
            ]
        },
        {
            "name": "Evolution-DecSync",
            "buildsystem": "simple",
            "build-commands": [
                "meson build",
                "sudo ninja -C build install"
            ],
            "sources": [
                {
                    "type": "git",
                    "url": "https://github.com/39aldo39/Evolution-DecSync",
                    "branch": "master"
                }
            ]
        },
```

This gives me the following error:

```
========================================================================
Building module libdecsync in /var/home/faust/Projects/org.gnome.Evolution/.flatpak-builder/build/libdecsync-7
========================================================================
Already on 'master'
Running: source /usr/lib/sdk/openjdk8/enable.sh && make
./gradlew linkReleaseSharedlinuxX64
Downloading https://services.gradle.org/distributions/gradle-6.5-bin.zip

Exception in thread "main" java.net.UnknownHostException: services.gradle.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:288)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1567)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:67)
	at org.gradle.wrapper.Download.download(Download.java:52)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
make: *** [Makefile:35: build/bin/linuxX64/releaseShared/libdecsync_api.h] Error 1
Error: module libdecsync: Child process exited with code 2
```

I don't know if I'm supposed to run a different script in `openjdk8` or if I'm missing something else.

**Comment by Sesivany** [comment]
I'm planning to make the Evolution flatpak more modular and provide some plugins as app extensions although I'm not sure I want to maintain every plugin people suggest. But extensions are separate entities on Flathub, so they can be maintained by other people. They just need entry points in the Evolution flatpak which I'm happy to make when asked.

The problem you're facing is that flatpak builds are done offline by default. The build script is trying to download gradle and fails because the network is not available. You can either build it with a specific switcher that makes the network available (this is possible for local builds, not allowed on Flathub) or add gradle as module to the manifest, so that it's downloaded before the build starts.
